name: loner
channels:
  - pytorch
  - anaconda
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - anndata=0.6.18=py_0
  - matplotlib
  - pandas=0.24.1=py36he6710b0_0
  - pip=19.0.3=py36_0
  - pytorch=1.0.1=py3.6_cuda10.0.130_cudnn7.4.2_2
  - scipy=1.2.0=py36h7c811a0_0
  - seaborn=0.9.0=py36_0
  - setuptools=40.8.0=py36_0
  - pyyaml
  - pip:
    - leidenalg==0.7.0
    - llvmlite==0.28.0
    - numba==0.43.0
    - numpy==1.14.6
    - python-igraph==0.7.1.post6
    - scikit-learn==0.19.2
    - scvi==0.3.0
    - umap-learn==0.3.7

